### ISSUE TITLE
Use ABC helper class when defining abstract base classes

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion-Cirq#246]
@babbush has expressed worry that the appearance of the word "metaclass" makes the code less readable because it will confuse people who don't know what a metaclass is. Since our only usage of metaclasses so far is `abc.ABCMeta`, we can use the helper class `abc.ABC` when creating abstract base classes, i.e.,
```
class MyABC(abc.ABC):
    pass
```
instead of
```
class MyABC(metaclass=abc.ABCMeta):
    pass
```

**Comment by Strilanc** [comment]
I agree that using `abc.ABC` would be better (though I disagree with not using metaclasses based on Ryan thinking they're weird). However, this doesn't get correctly translated into python 2.

Python 3:

```
import abc

class C(abc.ABC):
    @abc.abstractmethod
    def r(self):
        pass

c = C()
```

Running with python 3 works:

```
$ python3 cirq/tmp.py 

Traceback (most recent call last):
  File "cirq/tmp.py", line 8, in <module>
    c = C()
TypeError: Can't instantiate abstract class C with abstract methods r
```

Transpiled:

```python
# coding=utf-8
from __future__ import absolute_import
import abc

class C(abc.ABC):
    @abc.abstractmethod
    def r(self):
        pass

c = C()
```

Running the file with `python2`:

```
$ python2 cirq/tmp.py 

Traceback (most recent call last):
  File "cirq/tmp.py", line 5, in <module>
    class C(abc.ABC):
AttributeError: 'module' object has no attribute 'ABC'
```

**Comment by babbush** [comment]
I never said not to use them! I didn't say that! I said to explain what you're doing when you do use them because otherwise physicists are going to have no idea what you're doing.

**Comment by babbush** [comment]
I just wanted Kevin to make more comments when using advanced features of the language that are likely foreign to the vast majority of our users.

**Comment by Strilanc** [comment]
Point taken. I will caution that it is hard to judge what is and isn't familiar or "basic", though I do suspect metaclasses are known by fewer people than e.g. the difference between `/` and `//` when dividing.

**Comment by babbush** [comment]
I would wager that fewer than 5% of our users have any idea what a metaclass is.
