### ISSUE TITLE
Build breaks with GitHub Cirq

### ISSUE THREAD

**Issue by kevinsung** [quantumlib/OpenFermion-Cirq#331]
On executing `import openfermioncirq` I get

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sungkevin/Projects/OpenFermion-Cirq/openfermioncirq/__init__.py", line 13, in <module>
    from openfermioncirq.gates import (
  File "/home/sungkevin/Projects/OpenFermion-Cirq/openfermioncirq/gates/__init__.py", line 36, in <module>
    from openfermioncirq.gates.four_qubit_gates import (
  File "/home/sungkevin/Projects/OpenFermion-Cirq/openfermioncirq/gates/four_qubit_gates.py", line 190, in <module>
    DoubleExcitation = DoubleExcitationGate()
TypeError: Can't instantiate abstract class DoubleExcitationGate with abstract methods num_qubits
```

**Comment by ncrubin** [comment]
This is a symptom of needed a version lock bump.  I believe PR #326 attempts to address this but likely needs to have OpenFermion-Cirq locked to the 0.5.dev release of Cirq.
