### ISSUE TITLE
Issue with tutorial from documentation

### ISSUE THREAD

**Issue by HiggsBoson3310** [quantumlib/OpenFermion-Cirq#342]
I have been running the tutorial shown in the documentation and I stumbled upon an error from the source code. I am running python 3.7.0 in Windows and have basically copied the code provided in the documentation. 
My error comes when trying to use the run_sweep function of the simulator. The error is the following

```
Traceback (most recent call last):
  File "tutorial.py", line 104, in <module>
    results = simulator.run_sweep(circuit, params=sweep, repetitions=100) 
  File "C:\Users\migue\Anaconda3\lib\site-packages\cirq\sim\simulator.py", line 85, in run_sweep
    repetitions=repetitions)
  File "C:\Users\migue\Anaconda3\lib\site-packages\cirq\sim\sparse_simulator.py", line 121, in _run
    return self._run_sweep_sample(resolved_circuit, repetitions)
  File "C:\Users\migue\Anaconda3\lib\site-packages\cirq\sim\sparse_simulator.py", line 134, in _run_sweep_sample
    perform_measurements=False):
  File "C:\Users\migue\Anaconda3\lib\site-packages\cirq\sim\sparse_simulator.py", line 231, in _base_iterator
    indices))
  File "C:\Users\migue\Anaconda3\lib\site-packages\cirq\protocols\apply_unitary.py", line 208, in apply_unitary
    result = func(args)
  File "C:\Users\migue\Anaconda3\lib\site-packages\cirq\ops\gate_operation.py", line 107, in _apply_unitary_
    default=NotImplemented)
  File "C:\Users\migue\Anaconda3\lib\site-packages\cirq\protocols\apply_unitary.py", line 222, in apply_unitary
    out=args.available_buffer)
  File "C:\Users\migue\Anaconda3\lib\site-packages\cirq\linalg\transformations.py", line 214, in apply_matrix_to_slices
    out[s_i] *= matrix[i, i]
TypeError: ufunc 'multiply' output (typecode 'O') could not be coerced to provided output parameter (typecode 'F') according to the casting rule ''same_kind''
```

 Thank you for the help

**Comment by vtomole** [comment]
Could you please post the program you are trying to run?

Thank you.

**Comment by HiggsBoson3310** [comment]
[tutorial.txt](https://github.com/quantumlib/OpenFermion-Cirq/files/3055269/tutorial.txt)

**Comment by kevinsung** [comment]
This program does not use OpenFermion-Cirq. Is there a reason you posted it here instead of at Cirq?

**Comment by Strilanc** [comment]
Interesting. When I run the provided code, it completes successfully.

```
[cirq.GridQubit(0, 0), cirq.GridQubit(0, 1), cirq.GridQubit(0, 2), cirq.GridQubit(1, 0), cirq.GridQubit(1, 1), cirq.GridQubit(1, 2), cirq.GridQubit(2, 0), cirq.GridQubit(2, 1), cirq.GridQubit(2, 2)]
Transverse field: [[-1.0, 1.0, 1.0], [1.0, -1.0, -1.0], [-1.0, -1.0, 1.0]]
Columns coupling: [[-1.0, 1.0], [1.0, -1.0], [1.0, 1.0]]
Rows coupling: [[1.0, -1.0, -1.0], [1.0, -1.0, -1.0]]
                                                             ┌──────────────┐   ┌────────┐   ┌──────────────┐           ┌──────────────┐
(0, 0): ───X^alpha───X───────────────────@─────────X─────────────────@─────────────────────────────────────────────────────────────────────────M('x')───
                                         │                           │                                                                         │
(0, 1): ───X^alpha───Z^beta────X─────────@^gamma───X──────────@──────┼───────────X────────────@─────────────────X──────────────────────────────M────────
                                                              │      │                        │                                                │
(0, 2): ───X^alpha───Z^beta───────────────────────────────────@^gamma┼───────────X────────────┼──────@──────────X──────────────────────────────M────────
                                                                     │                        │      │                                         │
(1, 0): ───X^alpha───Z^beta────@─────────────────────────────────────@^gamma──────@───────────┼──────┼─────────────────────────────────────────M────────
                               │                                                  │           │      │                                         │
(1, 1): ───X^alpha─────────────@^gamma───X─────────@──────────X──────────────────X┼───────────@^gamma┼──────────X───X────@─────────────────X───M────────
                                                   │                              │                  │                   │                     │
(1, 2): ───X^alpha───X─────────────────────────────@^gamma────X──────────────────X┼──────────────────@^gamma────X───X────┼──────@──────────X───M────────
                                                                                  │                                      │      │              │
(2, 0): ───X^alpha───@────────────────────────────────────────────────────────────@^gamma────────────────────────────────┼──────┼──────────────M────────
                     │                                                                                                   │      │              │
(2, 1): ───X^alpha───@^gamma───@─────────X───────────────────────────────────────────────────────────────────────────────@^gamma┼──────────X───M────────
                               │                                                                                                │              │
(2, 2): ───X^alpha───Z^beta────@^gamma───X──────────────────────────────────────────────────────────────────────────────────────@^gamma────X───M────────
                                                             └──────────────┘   └────────┘   └──────────────┘           └──────────────┘
OrderedDict([('alpha', 0.1), ('beta', 0.1), ('gamma', 0.1)]) -0.9
OrderedDict([('alpha', 0.1), ('beta', 0.1), ('gamma', 0.30000000000000004)]) -0.54
OrderedDict([('alpha', 0.1), ('beta', 0.1), ('gamma', 0.5)]) -1.16
OrderedDict([('alpha', 0.1), ('beta', 0.1), ('gamma', 0.7000000000000001)]) -1.1
OrderedDict([('alpha', 0.1), ('beta', 0.1), ('gamma', 0.9)]) -0.62
[...]
OrderedDict([('alpha', 0.9), ('beta', 0.9), ('gamma', 0.30000000000000004)]) 0.98
OrderedDict([('alpha', 0.9), ('beta', 0.9), ('gamma', 0.5)]) 0.92
OrderedDict([('alpha', 0.9), ('beta', 0.9), ('gamma', 0.7000000000000001)]) 0.72
OrderedDict([('alpha', 0.9), ('beta', 0.9), ('gamma', 0.9)]) 1.06
```

**Comment by Strilanc** [comment]
Moved to Cirq https://github.com/quantumlib/Cirq/issues/1505
